# Generated by Django 4.2.26 on 2025-12-04 22:25

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('careplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careplan',
            name='edit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='careplan',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='careplan',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='care_plans', to='careplan.order'),
        ),
        migrations.AddField(
            model_name='careplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='careplan',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='CarePlanFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_content', models.TextField(help_text='Snapshot of original AI-generated content')),
                ('edited_content', models.TextField(help_text="User's edited version")),
                ('diff_data', models.JSONField(help_text='Structured diff: additions, deletions, summary')),
                ('feedback_text', models.TextField(help_text="User's free-form feedback")),
                ('feedback_categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, help_text='LLM-extracted categories', size=None)),
                ('extracted_issues', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, help_text='LLM-extracted specific issues', size=None)),
                ('extracted_suggestions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, help_text='LLM-extracted suggestions', size=None)),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text='Clinical impact severity (LLM-extracted)', max_length=10)),
                ('processed_for_prompt', models.BooleanField(default=False)),
                ('batch_number', models.IntegerField(blank=True, null=True)),
                ('extracted_rules', models.JSONField(blank=True, help_text='Rules extracted from batch processing', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('care_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='careplan.careplan')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['processed_for_prompt'], name='careplan_ca_process_2ad93e_idx'), models.Index(fields=['batch_number'], name='careplan_ca_batch_n_563554_idx')],
            },
        ),
    ]
